### ISSUE TITLE
Deployment issue on cpanel

### ISSUE THREAD

**Issue by mdnur89** [Raccoon254/cline#3]
Hi there, when I try deploy its not rendering any css files. 

I place project outside of public_html and public contents move to public_html and edit index to point to laravel project but its not rendering anything..

Please help me

**Comment by Raccoon254** [comment]
Hello, Please check the inspect panel and share the error
Or else check vite's documentation on running build css and js assets

**Comment by Raccoon254** [comment]
You can also message me and organize a meeting, I will try to help

**Comment by mdnur89** [comment]
Finally got it, path from build dir assets needed to go to main.blade.php

**Comment by mdnur89** [comment]
> You can also message me and organize a meeting, I will try to help 


Actually I will, I was just thinking of ideas are not yet in southern africa and will make a dent.
